### ISSUE TITLE
Basic single_cov2 approach question?

### ISSUE THREAD

**Issue by lokeyCEU** [multiz/multiz#3]
I have a multiple alignment file (maf) with 20 species in it that has overlapping alignment blocks. I want to filter for non-overlapping blocks. It appears single_cov2 can do this for pairwise maf files. However, it is unclear how the overlapping blocks are handled. Does single_cov2 remove the lower scoring block or is it something more basic? I would hope that when assessing overlapping blocks it would take the highest scoring block.

**Comment by rsharris** [comment]
Howdy, @lokeyCEU

I will have to pore through the single_cov2 source code to see what it is doing. I will try to do that today.

My expectation is that it uses *some* ranking method when deciding which block to keep. I'm not sure whether alignment score is the best choice, because long lower-identity blocks can score higher than shorter blocks that have higher sequence identity.

A related question is whether it might split blocks and discard only the parts with overlap.

**Comment by lokeyCEU** [comment]
Thanks for the quick response! 
My end goal is actually filtering out overlapping blocks for a multiple sequence alignment file with more than 2 species. Single_cov2 isn't recommended because it's for pairwise alignments correct? Do you know of another tool that could do this? I am having a hard time finding anything.

**Comment by rsharris** [comment]
Yes, I'm pretty sure single_cov2 only considers pairwise MAFs. I infer that from the brief usage info it provides if no command line arguments are given.

I'm not aware, specifically, of any tool that would handle overlaps beyond pairwise. But it has been roughly a decade since I've done much with multiple alignment myself.

You might try github.com/bxlab/bx-python which is a python package that supports a lot of operations on multiple alignments. MAF was the format that was originally written for (circa 2005). I'm listed as a contributor there but I really haven't been involved with it other than having contributed a few parts early on.

**Comment by rsharris** [comment]
I should have mentioned that I'm not the author of multiz. The author, Min Mei Hou, graduated and left our lab around 2007.

**Comment by lokeyCEU** [comment]
Fair enough haha. It seems to be the case for everyone i've reached out to that this is a problem of the past. Not sure if there is another way folks are going about getting conservation scores for non-model organisms these days?
The response is much appreciated.

 I did run single_cov2 on a multiple sequence alignment for the heck of it and it ran. The output seemed reasonable but I have no idea what sort of issues may have arisen. Trying to understand the source code today.

**Comment by rsharris** [comment]
Maybe someone in the UCSC browser group would have some advice regarding deriving conservation scores. Back in the day Adam Seipel would be the guy for that metric. You might try to track him down (he was at Cornell mid 200x's, not sure where he is now).

**Comment by lokeyCEU** [comment]
That's a good point the UCSC group has had to have dealt with this.

Thanks again for the help!

**Comment by rsharris** [comment]
Regarding your original question, I don't think single_cov2 considers scores when determining what to discard. I think what it does is throw away *all* overlapping pieces. So the result is alignment blocks that had no other alignment in the input. And some blocks are subdivided parts of blocks in the original.

Also beware that it rescores the resulting alignments, using a hard-coded scoring matrix.

**Comment by lokeyCEU** [comment]
Ahhh I see, that makes sense. Thank you for the clarification and advice!
